# Generated by Django 2.0.3 on 2018-04-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180319_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(blank=True, default=61999991010, help_text='Preencha com DDD e o número (sem símbolos especiais', verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
