# Generated by Django 2.0.3 on 2018-03-19 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Pedido'),
        ),
    ]
