# Generated by Django 2.0.3 on 2018-03-19 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180319_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_representacao', models.DateField(verbose_name='Data Início da Representação')),
                ('data_fim_representacao', models.DateField(verbose_name='Data Fim da Representação')),
                ('orgao_representado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orgao.Orgao', verbose_name='Órgão Representado')),
                ('representante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Representante')),
            ],
            options={
                'verbose_name': 'Representação',
                'verbose_name_plural': 'Representações',
                'ordering': ['orgao_representado', 'representante'],
            },
        ),
    ]
