# Generated by Django 2.0.3 on 2018-04-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_representacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
