# Generated by Django 2.0.3 on 2018-04-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_arquivoexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoexcel',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Arquivo Excel com a relação de obras.', upload_to='media/', verbose_name='Arquivo'),
        ),
    ]
